<?php

declare(strict_types=1);

namespace AgenticOrchestrator\Contracts;

use AgenticOrchestrator\Agents\AgentResponse;
use AgenticOrchestrator\Streaming\StreamResponse;
use Illuminate\Support\Collection;

/**
 * Core interface for all AI agents.
 *
 * An agent is an AI-powered entity that can receive input, use tools,
 * maintain memory, and produce responses. Agents can operate standalone
 * or be composed into workflows.
 */
interface AgentInterface
{
    /**
     * Get the agent's unique identifier.
     *
     * This is typically the class name for code-defined agents
     * or a UUID for database-defined agents.
     */
    public function getId(): string;

    /**
     * Get the agent's display name.
     *
     * Human-readable name shown in dashboards and logs.
     */
    public function getName(): string;

    /**
     * Get the agent's description.
     *
     * Explains what the agent does, useful for agent selection
     * and documentation.
     */
    public function getDescription(): string;

    /**
     * Get the LLM model identifier.
     *
     * E.g., 'gpt-4o', 'claude-3-5-sonnet-20241022', 'llama3.2'
     */
    public function getModel(): string;

    /**
     * Get the LLM provider name.
     *
     * E.g., 'openai', 'anthropic', 'ollama'
     */
    public function getProvider(): string;

    /**
     * Get the system instructions/prompt.
     *
     * The main instructions that define the agent's behavior,
     * personality, and capabilities.
     */
    public function instructions(): string;

    /**
     * Process a message and return a response.
     *
     * This is the main entry point for agent interaction.
     * The agent will process the message, potentially use tools,
     * and return a complete response.
     *
     * @param  string  $message  The user's message
     * @param  array<string, mixed>  $context  Additional context to include
     */
    public function respond(string $message, array $context = []): AgentResponse;

    /**
     * Process a message with streaming response.
     *
     * Similar to respond(), but returns a stream that yields
     * chunks as they are generated by the LLM.
     *
     * @param  string  $message  The user's message
     * @param  array<string, mixed>  $context  Additional context to include
     */
    public function stream(string $message, array $context = []): StreamResponse;

    /**
     * Get all available tools for this agent.
     *
     * Returns a collection of ToolInterface implementations
     * that this agent can use.
     *
     * @return Collection<int, ToolInterface>
     */
    public function getTools(): Collection;

    /**
     * Get the memory instance for this agent.
     *
     * Memory persists information across conversations
     * and enables semantic search capabilities.
     */
    public function getMemory(): MemoryInterface;

    /**
     * Delegate a task to another agent.
     *
     * Allows agents to work together by passing tasks
     * to specialized sub-agents.
     *
     * @param  AgentInterface  $agent  The agent to delegate to
     * @param  string  $task  The task description
     * @param  array<string, mixed>  $context  Additional context
     */
    public function delegate(AgentInterface $agent, string $task, array $context = []): AgentResponse;

    /**
     * Check if this agent can be delegated to.
     *
     * Some agents may be configured to only operate
     * as top-level agents and not accept delegations.
     */
    public function canBeDelegate(): bool;

    /**
     * Get the agent's full configuration.
     *
     * Returns all configuration including model settings,
     * memory config, capabilities, etc.
     *
     * @return array<string, mixed>
     */
    public function getConfig(): array;
}
